apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meeseeks-ui-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: "letsencrypt-http"
spec:
  ingressClassName: traefik
  rules:
    - host: meeseeks.kailas.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: meeseeks-ui-service
                port:
                  number: 80
  tls:
    - hosts:
        - meeseeks.kailas.cloud
      secretName: meeseeks-tls
