name: Valkey Operator Build

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "shared/valkey/operator/**"
      - ".github/workflows/valkey-operator-build.yml"
  pull_request:
    paths:
      - "shared/valkey/operator/**"
      - ".github/workflows/valkey-operator-build.yml"

env:
  REGISTRY: ghcr.io

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25
      - name: Display Go version
        run: go version
      - name: Build
        run: make V=1
        working-directory: shared/valkey/operator

  build-operator-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25
      - name: Build
        run: make V=1
        working-directory: shared/valkey/operator
      - name: Extract metadata (Operator tags, labels) for Docker
        id: meta_operator
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/valkey-operator
          tags: |
            type=raw,value=${{ github.sha }}
      - name: Build Operator image
        uses: docker/build-push-action@v6
        with:
          file: shared/valkey/operator/Dockerfile.controller
          context: shared/valkey/operator
          push: false
          tags: ${{ steps.meta_operator.outputs.tags }}
          labels: ${{ steps.meta_operator.outputs.labels }}
